name: Docs

on:
  pull_request:
    paths: ["**.tf"]

permissions:
  contents: write

jobs:
  terraform-docs:
    name: Generate terraform-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: terraform-docs/gh-actions@v1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
